### ISSUE TITLE
MPLogger fails when it can't properly decode log messages 

### ISSUE THREAD

**Issue by dreisman** [citp/OpenWPM#144] opened 2017-04-18 19:55 UTC
It appears that the MPLogger can't decode some log messages it receives. For instance, the extension logs HTTP POST information that doesn't decode properly. It appears that the same reason the browser can't decode the POST payload causes the MPLogger to fail in the same way. It doesn't appear to be killing MPLogger, but it leads to messy logs and should be investigated a bit more to ensure my characterization is correct.

Traceback examples:

}!?A<2?:?F??Pj?KըI ?r8Yo????i?.??9??(?Է??/?$?B?>\\u0011?0x\\\\\\td??X_??}Ȧ?D?8Q?ą?\\r?1b?ϸ???~?$6??4?\\u001bɇ[\\u001aB?\\u000f\\u001bJ?\\u00135?7?A?.??`?E????!G\\u000e???YZ\\u000e?\\u000e??Z?^?l\\u001c??s^?KbH\\\"_\\r?\\u0014o?|???_\\u001fd???\\u0005??\\u0012ͯ<??Oo??\\u001f9\\u0004S?? ??ƹLN??\\u0014?\\u0006\\u0011??}|U\\u0013Y!??TI??76?bC\\u0004?$??S[\\u0012 \\u0012\\u001b\\\"??kU՜\\bE\\u0004X\\n???mߪ?????/9?w?\\u0000b?n\\b????\\\"\\u000f???\\u001f\\u001d?V-\\u0017\\u0007?\\u001f8???%?&\\u001f???\\u0005\\\\?}?1??Blˈ\\u0018k???H\\u001d~??W?*=?A???4J?ݻ\\r??'{\\u0000wyqo?0$????G???O?mɆi????́?ҳ??\\bo!ҥ?m?~\\u0001?\\u0011?qR?H?d?K?#\\u001f????/)\\u001b*????4?V??G???l??\\u0002?5\\u0016I?OɃs\\u0013z?\\u0012C??.ځ\\u001e\\u000bБ??\\n\\f4?;cW?>+}?yv\\u0002?\\u000eU\\u0003)'??Qn??t\\u0004?%?\\u0011<#?\\f?\\u0016\\u0012wT\\u0013?9??\\\\??`??/?W?U?L???\\t>.\\u0010_?ܧ?a??????1?\\u0014???i???\\f\\u0019\\u001f??z?\\n???|\\u0001\\b?? ???p?\\u001b\\u0004aە?U?f섭?L?۸??\\u0001??X^\\u001d??!?\\u001do???G????\\u001f?mPn\\u0019p???\\u0006q\\\\?\\u001a\\u0014RXx(\\b?ҙIГ4\\u0016$b?g????K?y?=???؀`??H}v?f?q?ApG\\u001d\\u0019???*R1䝣\\ni\\u0015?;-\\u0004c??#???С??h??\\u0017?֞\\u0018r?S\\u000f??+\\u001atO?a?cd{?r????\\u0012^M\\u0016a\\u0005i?Kc? +O?ih??k??\\u0011?ۘ??\\u0002??x;\\\\\\\"z?l?x?;??????\\u0007\\n\",\"args\":null,\"exc_info\":null,\"func\":null}"] 

Traceback (most recent call last): 

File "/home/ubuntu/openwpm-census/OpenWPM/automation/SocketInterface.py", line 65, in _handle_conn 
msg = json.loads(msg) 
File "/usr/lib/python2.7/json/__init__.py", line 339, in loads 
return _default_decoder.decode(s) 
File "/usr/lib/python2.7/json/decoder.py", line 364, in decode 
obj, end = self.raw_decode(s, idx=_w(s, 0).end()) 
File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode 
obj, end = self.scan_once(s, idx) 
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 124: invalid continuation byte

AND:

Error de-serializing message: ["EXT","{\"name\":\"Extension-Logger\",\"level\":10,\"pathname\":\"FirefoxExtension\",\"lineno\":1,\"msg\":\"POST data is not parseable:URIError: malformed URI sequence EncodingType: PostDataLength:1483 PostDataType:string PostData:e?ǲ@)?\\u0002)\\\\??Ͽ??_??W????5??g_??W?????_?Ox?\\u0006i??\\u0002???????W?\\u0007{??B?_????7_?򫿀?O38/???~?\\u0004?~?D\\u0011?/??_?ŗ??˟\\u0000?/??????\\u001f??2?\\u0017?[º?6#H;@\\u0006\\u0019\\u0011??*j•H????^?[\\u001a?u2NT\\u000bY|)k\\u0005?\\u0019k\\u001f?\\u000e???gU??3!N??AQɲ\\u0003?x????d?%??/kb&K??kՆ?j?Ũ????Vq?Bʼ?h?C\\u001a?\\u0013??\\u0014?y?~?\\u0018V`b??oR\\u0007C?]\\r\\\\+4\\u0013?\\u000e&?\\\"??

**Comment by englehardt** [comment] 2017-04-26 16:40
Can you reproduce the error on a specific site? If so, would you mind to provide the site url?

**Comment by englehardt** [comment] 2017-05-20 18:50
The second traceback you list is caused by lines https://github.com/citp/OpenWPM/blob/1b0bafbba5bf9fd3d9049d013a7e589e12cc6fc3/automation/Extension/firefox/lib/http-post-parser.js#L165-L167.

I think we can prevent this by ensuring all messages are utf-8 in the logger: https://github.com/citp/OpenWPM/blob/1b0bafbba5bf9fd3d9049d013a7e589e12cc6fc3/automation/Extension/firefox/lib/loggingdb.js#L75

**Comment by englehardt** [comment] 2017-05-20 19:45
Fixed in: b136c9012e0ea1a84f85ef79c1abd0b00986cda7. Let's check the new crawl data to verify.

**Comment by englehardt** [comment] 2017-06-20 17:41
Verified fixed in new crawl data.

**Closed by englehardt** 2017-06-20 17:41 UTC
Labels: bug, needs-verification
